[phases.setup]
nixPkgs = ["php82", "php82.extensions.curl", "php82.extensions.mbstring", "php82.extensions.openssl", "php82.extensions.pdo", "php82.extensions.pdo_sqlite", "php82.extensions.sqlite3", "php82.extensions.xml", "php82.extensions.zip"]

[phases.install]
cmds = ["composer install --no-dev"]

[phases.build]
cmds = ["php artisan optimize:clear"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
