[phases.setup]
nixPkgs = ["php81", "php81.extensions.curl", "php81.extensions.mbstring", "php81.extensions.openssl", "php81.extensions.pdo", "php81.extensions.pdo_sqlite", "php81.extensions.sqlite3", "php81.extensions.xml", "php81.extensions.zip"]

[phases.install]
cmds = ["composer install --no-dev"]

[phases.build]
cmds = ["php artisan optimize:clear"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
